### ISSUE TITLE
Text on a path just outputs NaNs for the path points

### ISSUE THREAD

**Issue by mvujovic** [adobe-research/svgObjectModelGenerator#108]
1. In PS, draw a path (e.g. a line).
2. Select the type tool and click on the line when the cursor changes.
3. Type some text.
4. Generate Assets for the layer as SVG.

The SVG file will contain NaNs for the path points.

If you fix the NaN bug by changing instances of code like "points[0].anchor.horizontal" to "points[0].anchor.horizontal.value" in svgOMGeneratorText.js::_computeTextPath, the text isn't positioned correctly either. Often times, the text appears outside of the SVG bounds (visible if you open the SVG file in Illustrator). Also, the bounds of the SVG element match the bounds of the path, not the bounds of the text rendering, so text looks clipped.

**Comment by dirkschulze** [comment]
Ah, didn't see this bug. Yes, it was a regression with generator and I just fixed it. Could you confirm it please so that I can close?

**Comment by mvujovic** [comment]
@dirkschulze: Just tried it out. Looks good!

There's still the issue that the asset bounds are fit to the path bounds and clip some of the text, but I'll file that separately. We just need better text metrics from PS to fix that.

**Comment by mvujovic** [comment]
@dirkschulze Filed #142 for text on a path clipping issue.
