### ISSUE TITLE
100%%

### ISSUE THREAD

**Issue by DmitryBaranovskiy** [adobe-research/svgObjectModelGenerator#130]
At [this example](https://github.com/adobe-research/svgObjectModelGenerator/blob/master/tests/data/text-on-path.svg?short_path=ae7efff#L57) you can clearly see the bug with `100%%` being put as `x` attribute:
```xml
  <text x="100%%" class="cls-3"><textPath xlink:href="#text-path-6" startOffset="100%">
    <tspan x="100%" startOffset="100%" class="cls-20">Text path</tspan>
  </textPath></text>
```
There is also a smaller issue with `startOffset` being put on tspan.

**Comment by imaderyc** [comment]
confirmed fixed
