### ISSUE TITLE
Corrupted SVG file when extracting group with text

### ISSUE THREAD

**Issue by imaderyc** [adobe-research/svgObjectModelGenerator#152]
https://watsonexp.corp.adobe.com/#bug=3857733

works in latest Crema and PS Mainline build, so seems like it was introduced by recent changes in svgObjectModelGenerator master

1. open bugfile (file is also posted at https://www.dropbox.com/s/ogmkuxyxey298l9/textInGroup.psd?dl=0)
2. extract Svg for group (not the text layer inside group, but the group itself)
3. check svg file

Result: there is only 1 line in svg file, <path id="text-path-1"

**Comment by imaderyc** [comment]
@dirkschulze @DmitryBaranovskiy please look at this bug; we want to take SVG changes into Crema build, but this bug is new, it doesn't reproduce in shipping Crema build

**Comment by dirkschulze** [comment]
I can not confirm the output with the latest svgOMG/generator-assets version:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" width="359" height="747" viewBox="0 0 359 747">
  <defs>
    <style>

      .cls-4, .cls-6 {
        font-size: 40px;
      }

      .cls-3 {
        fill: aqua;
      }

      .cls-6 {
        fill: #b62055;
        font-family: "Arial-BoldMT";
        font-weight: bold;
      }
    </style>

    <path id="text-path-1" d="M48,360.75H182.5"/>
  </defs>
  <g id="groupwithtextpng-groupwithtextsvg">
    <ellipse cx="224" cy="667" rx="135" ry="80" class="cls-3"/>
    <text class="cls-4"><textPath xlink:href="#text-path-1">
      <tspan class="cls-6">some text here</tspan>
    </textPath></text>
  </g>
</svg>
```

**Comment by dirkschulze** [comment]
What you see is probably the result before the text path patch which doesn't seem to work for you either. I recommend that you reinstall all dependencies with a fresh installation. Maybe this fixes the issue?

The output above is with the latest version of Crema as well btw.

**Comment by imaderyc** [comment]
weird, I can't reproduce it anymore, with the same build/same setup. I wonder if restarting machine 'fixed' it?
